### ISSUE TITLE
POD 安装 SD 版本容易冲突，建议fork下一个版本，SDK自己管理就好了

### ISSUE THREAD

**Issue by jeremyzj** [BotBrain/BotBrainFeed#1]

**Comment by BotBrain** [comment]
1、SDK中已经降低依赖库的版本号，AFNetworking支持最低3.0.0，SDWebImage支持最低3.7.0。
2、你说的这个方案比较适合你那边来做这个操作，你fork后可以修改BotBrainFeed.podspec文件。
谢谢。
